feat: useGestures or remove gestures
NikhilVadoliya/Flutter_slider_drawer pull request #34
Opened 2024-02-22 04:58 UTC by Segatti

Issue: I was creating an app with a Tinder-style interface, and the main widget, which has horizontal swipe gestures, was conflicting with the GestureDetector in that widget used to open the side menu.

Solution: I created an attribute to disable the GestureDetector if necessary, and it worked perfectly for my purpose. Since I noticed other developers facing the same issue on Github, I decided to create this pull request to help everyone.

2025-03-17 09:40 UTC, NikhilVadoliya requested changes

2025-03-17 09:40 UTC, NikhilVadoliya commented on example/android/app/src/main/AndroidManifest.xml
> +            android:exported="true"
Hello @Segatti , What's the reason to add this?

2025-03-17 09:40 UTC, NikhilVadoliya commented on lib/src/slider.dart
> +    this.useGestures = true,
Hello @Segatti , with the help of `isDraggable` we can stop the Gesture for open and close. Can you please verify it ?

2025-03-17 09:40 UTC, NikhilVadoliya commented on lib/src/slider.dart
> +          child: (widget.useGestures)
we can use "isDraggable". Can you please remove new added variable check with this variable?

2025-03-17 09:40 UTC, NikhilVadoliya commented on pubspec.yaml
> +version: 2.1.6
version name should be 2.1.4 because this is a minor feature/ hotfixes

2025-03-28 20:09 UTC, Segatti commented on example/android/app/src/main/AndroidManifest.xml
> +            android:exported="true"
On Android 12 (API 31) and higher, if a component has an **intent filter (`intent-filter`)**, you are **required** to explicitly define `android:exported`. Otherwise, the app will **fail to compile**.

2025-03-28 20:20 UTC, Segatti commented on lib/src/slider.dart
> +    this.useGestures = true,
Hi @NikhilVadoliya , I removed `useGesture` and I'm using `isDraggable` for the condition.

2025-03-28 20:21 UTC, Segatti commented on lib/src/slider.dart
> +          child: (widget.useGestures)
Fixed

2025-03-28 20:21 UTC, Segatti commented on pubspec.yaml
> +version: 2.1.6
Fixed

2025-03-28 20:26 UTC, closed without merging

2025-03-28 20:45 UTC, Segatti commented
I saw that you updated the package and placed the conditional first, I don't think my PR is needed anymore.